version: '2'

services:
  # sql
  mysql:
    image: mysql:8.0.29
    ports:
      - 3306:3306
    volumes:
      - ./conf/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
  canal:
    image: canal/canal-server:v1.1.6
    ports:
      - 11111:11111
    environment:
      - canal.instance.master.address=mysql:3306
      - canal.instance.dbUsername=root
      - canal.instance.dbPassword=root
      - canal.instance.filter.regex=db.configure
      # mq configure
      - canal.serverMode=kafka
      - canal.mq.servers=kafka:9092
      - canal.mq.topic=configure-topic
      - canal.mq.flatMessage=true
    depends_on:
      - mysql
      - kafka

  # nosql
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181

  # mq
  rabbitmq:
    image: rabbitmq:3.11.1-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./conf/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./libs/rabbitmq_delayed_message_exchange-3.11.1/:/opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.11.1/
  kafka:
    image: bitnami/kafka
    ports:
      - 9093:9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://centos:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
