server:
  port: 5678

spring:
  shardingsphere:
    datasource:
      names: ds0, ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://centos:3306/db?allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: root
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://centos:3306/db?allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: root
    rules:
      sharding:
        tables:
          tb_config:
            actual-data-nodes: ds0.tb_config
          tb_session:
            actual-data-nodes: ds1.tb_session
  redis:
    host: centos
    port: 6379
  cloud:
    zookeeper:
      connect-string: centos:2181
  rabbitmq:
    host: centos
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: centos:9093

config:
  delay: 1800000 # 0.5h
